name: CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  # Quality checks job - runs on all branches
  quality-checks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run linting
        run: npm run lint

      - name: Run type checking
        run: npx tsc --noEmit

      - name: Run tests
        run: npm test --if-present

      - name: Build project
        run: npm run build

      - name: Upload build artifacts (if build fails)
        if: ${{ failure() }}
        uses: actions/upload-artifact@v4
        with:
          name: failed-build-logs
          path: |
            .next/
            dist/
            build/
            npm-debug.log

      - name: Comment on PR with failure details
        if: ${{ failure() }}
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { issue: { number: issue_number }, repo: { owner, repo }  } = context;
            const message = `🚨 Quality checks failed. Please check the logs and fix the issues before merging.`;
            await github.rest.issues.createComment({
              owner,
              repo,
              issue_number,
              body: message
            });