name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    container:
      image: node:22-alpine

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm ci

      - name: Run linter
        run: npm run lint

      - name: Run tests
        run: npm test --if-present

      - name: Build project
        run: npm run build

      - name: Upload build artifacts (if build fails)
        if: ${{ failure() }}
        uses: actions/upload-artifact@v4
        with:
          name: failed-build-logs
          path: |
            .next/
            dist/
            build/
            npm-debug.log

      - name: Notify on failure
        if: ${{ failure() }}
        uses: actions/github-script@v6
        with:
          script: |
            const message = `🚨 CI/CD pipeline failed on **${context.workflow}**.
            Please check the logs before merging.`;
            console.log(message);
