name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest  # GitHub-hosted runner
    container:
      image: node:22-alpine  # Lightweight Node.js Alpine container

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 9
          run_install: false

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run linter
        run: pnpm lint

      - name: Run tests
        run: pnpm test --if-present

      - name: Build project
        run: pnpm build

      - name: Upload build artifacts (if build fails)
        if: ${{ failure() }}
        uses: actions/upload-artifact@v4
        with:
          name: failed-build-logs
          path: |
            .next/
            dist/
            build/
            pnpm-debug.log

      - name: Notify on failure
        if: ${{ failure() }}
        uses: actions/github-script@v6
        with:
          script: |
            const message = `🚨 CI/CD pipeline failed on **${context.workflow}**.
            Please check the logs before merging.`;
            console.log(message);
