name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest  # Needed for GitHub Actions runners
    container:
      image: node:22-alpine  # Use lightweight Node.js Alpine image

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 9 # or the pnpm version you use in package.json
          run_install: false

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run linter
        run: pnpm lint

      - name: Run tests
        run: pnpm test --if-present

      - name: Build project
        run: pnpm build

      - name: Upload build artifacts (for debugging if needed)
        if: ${{ failure() }}
        uses: actions/upload-artifact@v4
        with:
          name: failed-build-logs
          path: |
            .next/
            dist/
            build/
            pnpm-debug.log

      - name: Notify on failure
        if: ${{ failure() }}
        uses: actions/github-script@v6
        with:
          script: |
            const issue_number = context.issue?.number;
            const message = "🚨 CI/CD pipeline failed on **${context.workflow}**.\nPlease check the logs before merging.";
            if (issue_number) {
              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number,
                body: message
              });
            } else {
              console.log(message);
            }
