name: Build and Quality Checks

on:
  push:
    branches: [ main ]

jobs:
  build-and-checks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'pnpm'

      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 9
          run_install: false

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run linting
        run: pnpm lint

      - name: Run type checking
        run: pnpm exec tsc --noEmit

      - name: Run tests
        run: pnpm test --if-present

      - name: Build project
        run: pnpm build

      - name: Create build artifact
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: build-output
          path: |
            .next/
            dist/
            build/

      - name: Comment on commit with build status
        if: success()
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { repo: { owner, repo }, sha } = context;
            const message = `✅ Build successful! All quality checks passed.\n\nBuild artifacts are available as workflow artifacts.`;
            await github.rest.repos.createCommitComment({
              owner,
              repo,
              commit_sha: sha,
              body: message
            });

      - name: Notify on build failure
        if: failure()
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { repo: { owner, repo }, sha } = context;
            const message = `❌ Build failed. Please check the logs and fix issues before deploying.`;
            await github.rest.repos.createCommitComment({
              owner,
              repo,
              commit_sha: sha,
              body: message
            });